channels:
- conda-forge
- anaconda
dependencies:
- pandas
- geopandas
- numpy
- yaml
- pyyaml
- openpyxl
- pip
- conda-forge::pysal
- conda-forge::pyogrio
- python-dotenv
- statsmodels
- fiona
- xlrd=1.2
- appdirs
- mkl-service
- tqdm
- conda-forge::copulae
- pip:
  - census
  - us
  - sodapy
  - -e ../../packages/rputils
  - -e ../../packages/algi
  - -e ../../packages/thomas
  - censusdata
  - shareplum
  - pandasql
name: amats_cap_equity
