name: amats_cap_equity

channels:
  - conda-forge
  - anaconda

dependencies:
- pandas
- geopandas
- numpy
- yaml
- pyyaml
- openpyxl

- pip
- pip:
  - census
  - us
  - sodapy # socrate open data api for cdc places support
  - pygris # tiger spatial data
  - -e ../../packages/rputils
  - -e ../../packages/algi
  - -e ../../packages/thomas
    
